### ISSUE TITLE
[1] Pull request template만들기

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#1]
아래 URL을 참고해서 만들어주세요!
https://trustyoo86.github.io/github/2019/02/15/github-template.html

**Comment by yuriKIM-i3** [comment]
https://github.com/crane93/Issue-Maker/blob/master/.github/PULL_REQUEST_TEMPLATE.md
この感じでいいかな

**Comment by cheekykorkind** [comment]
良いと思います
