### ISSUE TITLE
MySQL5.7 인스톨

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#13]
- MySQL인스톨하고 초기 비밀번호 설정하기
https://galid1.tistory.com/296?category=761537
https://qiita.com/RyochanUedasan/items/9a49309019475536d22a

- MySQL 원격 접속 허용하기
https://galid1.tistory.com/349?category=761537

- 데이터베이스 설계 도구 인스톨
https://dev.mysql.com/downloads/workbench/

-  MySQL Workbench로 DB에 원격 접속
`2. 실행 중인 MySQL과 연결한다.` 까지 하면 됩니다.
https://gmlwjd9405.github.io/2018/05/09/mysql-workbench-guide.html

**Comment by yuriKIM-i3** [comment]
완료!

```
참고: 리눅스에서 mysql 입장하는법
>커맨드에 mysql -u root -p 입력하고 비밀번호 치면 끝
```

**Comment by cheekykorkind** [comment]
이슈 제목이 내용을 포괄하지 못한점은 미안합니다! 확인 부탁드립니다.
코멘트를 보고 생각해보면,
호스트머신(윈도우)에서 MySQL Workbench을 인스톨하고,
게스트머신(vagrant로 기동한 가상머신)에 MySQL Workbench로 원격 접속 성공하지 않은것으로 보입니다.
호스트 머신에 MySQL Workbench인스톨하고 게스트 머신에 원격 접속 성공했습니까?(성공이라면 close해도 좋습니다!)

**Comment by yuriKIM-i3** [comment]
😭

**Comment by yuriKIM-i3** [comment]
> https://gmlwjd9405.github.io/2018/05/09/mysql-workbench-guide.html

이 링크에 디비랑 원격접속하는 방법도 있나요? 
ssh로 들어가야하나요?

**Comment by yuriKIM-i3** [comment]
https://www.howtoforge.com/tutorial/how-to-enable-ssl-and-remote-connections-for-mysql-on-centos-7/

이렇게 원격접속 하는건가요?

**Comment by cheekykorkind** [comment]
https://www.howtoforge.com/tutorial/how-to-enable-ssl-and-remote-connections-for-mysql-on-centos-7/ 은 MySQL Workbench로 원격 접속하는 내용이 없군요.

https://gmlwjd9405.github.io/2018/05/09/mysql-workbench-guide.html 에 있습니다.
이번에 하려는 MySQL Workbench의 원격 접속에는 ssh 사용하지 않았습니다.
`1. MySQL Workbench에서 새로운 연결을 생성한다. ` 
`2. 실행중인 MySQL과 연결한다.` 
를 본인의 개발환경에 맞게 응용하면 됩니다!

**Comment by yuriKIM-i3** [comment]
![제목 없음](https://user-images.githubusercontent.com/44425582/58451115-110c6280-814d-11e9-86f0-fb3ba7c18c5d.png)

된다!
센세의 말에 잘 따르면 되는거였네요!

**Comment by yuriKIM-i3** [comment]
> https://qiita.com/RyochanUedasan/items/9a49309019475536d22a

여기서 설정했던 set variable들이 가상머신을 껐다 키면 초기화가 되있는데...
검색해보니 my.cnf파일에 적어두면 된다고하는데
그럼 my.cnf에 
```
SET GLOBAL validate_password_length=4;
SET GLOBAL validate_password_policy=LOW;
```
이렇게 적어두면 되나여?
라고하고 해봤지만 안됭이ㅏ얼

**Comment by cheekykorkind** [comment]
그런게 있었다니..
비밀번호 맘에 드는걸로 바꿔났으면, 그걸로 계속 로그인하면 되니까
패스워드 발리데이션 정책 그대로 둬도 되지 않을까요?

**Comment by cheekykorkind** [comment]
스샷에서 성공을 확인했으므로 클로즈 합니다!

**Comment by yuriKIM-i3** [comment]
> 그런게 있었다니..
> 비밀번호 맘에 드는걸로 바꿔났으면, 그걸로 계속 로그인하면 되니까
> 패스워드 발리데이션 정책 그대로 둬도 되지 않을까요?

비번 설정하고 몇번 더 설정할때 
비번 치라고 해서 쳤더니 보안수준 낮은 비번이라고 빠꾸먹은적이 몇번 있어서...
지금은 설정하느라 비번칠일이 많은거겠져?
나중에도 계속 피곤하면 그때 설정하겠슈

**Comment by yuriKIM-i3** [comment]
### mysql 한글깨짐 해결법
---
1.  /etc/my.cnf 로 이동
2. 파일에 아래의 내용을 추가
   ```
   collation-server = utf8_unicode_ci
   character-set-server = utf8
   skip-character-set-client-handshake
    ```
3. service mysqld restart 로 mysql 재구동

_주의!
한글깨짐 해결법을 하고 나서 데이터베이스를 추가해야한다
위의 방법은 기존의 데이터베이스에는 적용안된다
