### ISSUE TITLE
개발 스케쥴 작성해보기

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#16]
손으로 그려도 OK
엑셀로 만들어도 OK
만드는 도구는 뭐든 OK
다만, 같이 일하는 사람과 공유할수있는 형태로 만듭시다!

**Comment by yuriKIM-i3** [comment]
https://docs.google.com/spreadsheets/d/1YI8F5-mmVdAS4uckgigwI6PUJWI6p8sHYju5S4MZTxM/edit#gid=0
이런식으로 하나의 화면에 관한 필요한 스킬들을 나열하는건가요오

그리고... 하나의 작업에 걸리는 시간은 뭉뚱그려서 정할려구 합니당
이유
1. 나는 초보자이기때문
   html이나 jQuery를 써봤지만 많이 다뤄본게아니라서 하나하는데 시간이 오래 걸릴것 같소
   그런와중에 시메키리를 정해두면 시간은 다가오는데 만들어둔게 없음 >  스트레스로 타코야끼경보 1단계 발동
   이 될것 같습니다아...
2. 잘 만들기 위해
   비록 시간이 오래 걸려도 공들여서 만들면 더 잘 만들겠지요

というわけで、정확한 스케쥴은 없을거같습니다...
하지만 초반에 시간이 걸리지만 갈수록 익숙해져 시간 단축 할수있을거라 믿습니다

**Comment by cheekykorkind** [comment]
> 하나의 화면에 관한 필요한 스킬들을 나열하는건가요오
- 개발 스케쥴은 개발과정에서 소화할 태스크를 나열하고, 태스크별로 시간걸리는 시간을 정리한 것이라고 생각합니다.(1일 한칸에 색칠하기로 표현하건, 3일로 표현하건 표현법은 자유)

>  하나의 작업에 걸리는 시간은 뭉뚱그려서 정할려구 합니당
- 맞습니다. 태스크별로 걸리는 시간을 적으면 됩니다.

- `1. 나는 초보자이기때문`  에 대한 의견
개발 스케쥴에 기재하는 시간은 개발에 걸릴 시간량을 의미하기 때문에 `8월 15일 까지` 같은 시메키리와는 인상이 조금 다르다고 생각합니다.

정확한 스케쥴 예상은 매우 어려운 일입니다. 그래도 정확한 스케쥴 예상을 시도하면 좋습니다. 왜냐하면, 
- 스케쥴이 틀리는것을 확인하면서 전체적으로 현재 개발속도가 적절한지 파악할 수 있기 때문입니다.
- 현재 개발속도를 인식하게 되서, 남은 태스크를 조절하면서 `개발 완료` 라는 목표를 달성할 수 있기 때문입니다. 
- 스케쥴이 틀리는 경험을 반복하면 다음 예측의 정확도가 올라가기 때문입니다.
