### ISSUE TITLE
화면 설계서 만들기

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#17]
손으로 그려도 OK
워드, 엑셀로 만들어도 OK
자기가 아는 툴로 만들어도 OK
다만, 같이 일하는 사람과 공유 가능한 형태로 만듭시다!

**Comment by cheekykorkind** [comment]
사례 1) draw.io를 이용해서 만들었습니다.(내용 전달만 되면 손으로 그려도 상관없음)
- 로그인 화면 대략적으로 만들어봄
![issueMakerLogin](https://user-images.githubusercontent.com/22050468/58449396-55e0cb00-8146-11e9-8248-6ad7e97d8b1c.PNG)

**Comment by yuriKIM-i3** [comment]
구상중인데...
고민이 되는건
* 점점 깃 이슈의 화면과 똑같이 구상하고 있다는 것

물론 처음 목적이 깃이슈부분을 만든다! 지만 너무 똑같은것같아유
다른 화면을 만들려고 하니 감각이 부족해 생각은 안나고 😢 
같은화면 vs 다른화면  뭐가 좋을까요

**Comment by cheekykorkind** [comment]
개인적으로는 같은화면이 좋다고 생각합니다. 이유로는
- 우리는 백엔드에 집중하고 있기때문입니다. 
- 초심자가 새로운걸 만드는건 어렵기 때문입니다. 
- 기존 화면을 보면서 '이렇게 만드니까 어색해 보이지 않구나'라는 감각을 배울 수 있기때문입니다.

여기서 제안을 하자면,
먼저 같은화면으로 만들다가 여유가 있고 좋은 화면이 생각났다면 그때 추가로 만들어보는게 좋다고 생각합니다!

**Comment by yuriKIM-i3** [comment]
구글 드라이브 공유 참고 오네가이
https://drive.google.com/open?id=1emMEi0oRWzKLIYjh6gIIYcJXkn9OqRx9
