### ISSUE TITLE
DB설계서 만들기

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#18]
손으로 그려도 OK
워드, 엑셀로 만들어도 OK
자기가 아는 툴로 만들어도 OK
다만, 같이 일하는 사람과 공유 가능한 형태로 만듭시다!

**Comment by yuriKIM-i3** [comment]
구글 드라이브 공유신청 했슈
見てちょうだい 👀

**Comment by cheekykorkind** [comment]
확인하겠습니다아

**Comment by yuriKIM-i3** [comment]
https://docs.google.com/spreadsheets/d/1HpKV7qrFX56PA9ojPfSX8FZtirF0NRFZbl5Yb-yxVHU/edit#gid=181673145

소녀, 조언을 받아 만들어보았사옵니다 
💘

**Comment by cheekykorkind** [comment]
댓글 달았습니다!

2019년 6월 4일 (화) 오전 12:13, Yuri KIM <notifications@github.com>님이 작성:

**Comment by yuriKIM-i3** [comment]
https://docs.google.com/spreadsheets/d/1HpKV7qrFX56PA9ojPfSX8FZtirF0NRFZbl5Yb-yxVHU/edit#gid=181673145

도조

**Comment by cheekykorkind** [comment]
좋은거 같습니다!
본격 코드 작성전에 스케쥴을 한번 정리해봅시다👍
