### ISSUE TITLE
[2] 리눅스 유저 추가

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#2]
- 서버관리하면서 유저를 추가하거나 권한 부여하는 일이 많습니다.
- 무언가를 개발할때는 개발용 리눅스 유저를 만드는 습관을 추천합니다.

아래 URL을 참고해서 만들어봅시다!
https://zetawiki.com/wiki/%EB%A6%AC%EB%88%85%EC%8A%A4_%EA%B3%84%EC%A0%95_%EC%83%9D%EC%84%B1_useradd

**Comment by yuriKIM-i3** [comment]
crane으로 추가완료
