### ISSUE TITLE
[3] JDK인스톨

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#3]
- 앞으로 사용할 Gradle, Apache Tomcat에 필요합니다.

아래 URL을 참고해서 만들어봅시다!
https://blog.hanumoka.net/2018/04/30/centOs-20180430-centos-install-jdk/

- 한번 읽어두면 괜찮을 내용
JVM, JDK, JRE란 ( http://www.itworld.co.kr/news/110817 )

**Comment by yuriKIM-i3** [comment]
한번에 완료!
### 😀 ###
