### ISSUE TITLE
Gradle Spring Boot 프로젝트 만들어보기

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#7]
아래 URL을 참고해서 지금 프로젝트를 Spring Boot가 실행가능한 Gradle 프로젝트를 만듭시다!
https://spring.io/guides/gs/spring-boot/

**Comment by yuriKIM-i3** [comment]
> Spring Boot의 가장 큰 장점은 설정 파일이 사실상 전무하게 프로젝트를 당장 구동할 수 있다는 점인것 같습니다.

라고 하는데 스프링 처음 배우는 제가 설정파일같은거 안만져보고 스프링부트로 가도 크게 상관 없나요?
 ### 🤐 ###

**Comment by cheekykorkind** [comment]
스프링 설정 만져보고 스프링 부트를 하면 최고지만 그렇게 하기는 좀 아쉽다고 생각했습니다.
- 웹 개발의 세계가 스프링으로 통일되어 있다면 필수라고 생각하지만, 웹 개발의 세계는 다른 언어, 다른 언어의 프레임워크들이 난립하는 시대라서, 스프링 열심히 하는 메리트는 그렇게 없을거 같습니다.

- 시간적인 여유를 생각해볼때, 스프링부트건 스프링이건 화면을 만들고, 비즈니스 로직(내가 만들고 싶어하는 로직)을 만드는 부분은 같다고 하니까 이부분을 중심으로 하면 좋다고 생각했습니다.
