### ISSUE TITLE
Github인스톨

### ISSUE THREAD

**Issue by cheekykorkind** [crane93/Issue-Maker#8]
## 조건
- centos7에 깃허브 인스톨하기
- ssh로 깃허브 사용하기

## 방법
구글에서 자유롭게 검색해서 인스톨해봅시다

**Comment by crane93** [comment]
![e](https://user-images.githubusercontent.com/44425582/57866747-cdefec80-783a-11e9-8762-2e0b196e6aa9.png)

**Comment by yuriKIM-i3** [comment]
https://qiita.com/shimisunet/items/1b9568ff62a1550a931b#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB

위의 사이트를 참고하여 ssh설정 하였다
